### ISSUE TITLE
A bug in defining S

### ISSUE THREAD

**Issue by Unreal2RW** [obolo/freeRaptor#9]
When I tried this program by setting K = 64 or 128, the precoding matrix became singular, which was quite abnormal as rfc5053 guaranteed that the matrix must be invertible.
The bug comes from the way of defining S (the number of LDPC symbols) in r10_compute_params of raptor10.c. It doesn't match the definition in rfc5053, where S is the smallest **prime integer** such that S >= ceil(0.01*K) + X.

**Comment by obolo** [comment]
Yeah, it is highly likely. It setup this project with high hopes, that soon crushed as life gave me more high priority stuff to do. I'll try to check the bug and fix it if someone won't do it before. For the moment thanks a lot for reporting!
